### ISSUE TITLE
LayerID - name string warning is too strict

### ISSUE THREAD

**Issue by demisjohn** [demisjohn/ASML_JobCreator#31]
Currently pops a warning saying that underscores `_` are not allowed, because I checked this with
`LayerID.isalnum()` (alphanumeric).

But actually underscores are allowed, and 15 char. max.

––––––––––––––

From Miguel Daal:

There is also a slight layer naming issue with your code. I never got around to telling you until now. I modified my copy to fix it:

These Layer ID errors result in the layer names being default values of "1 - 1" and "2 -2" etc.
`Layer # 1: Layer ID string "WG_CLEAROUT_LYR" is invalid, setting ID to layer number.`

`WG_CLEAROUT_LYR = MyJob.Layer( LayerID="WG_CLEAROUT_LYR" )` gives the error
`WG_CLEAROUT_LYR = MyJob.Layer( LayerID="1" )` gives no error

_This is being caused by this bit of code in exportlib.py :_
    if DEBUG(): print("Generating Text Section 'LAYER_DEFINITION'")
    for i,L in enumerate(JobObj.LayerList):
        if DEBUG(): print( "Layer #%i, ID='%s'" %(i, str(L.LayerID) ) )
        s += "START_SECTION LAYER_DEFINITION\n"
        s = add(s, "LAYER_NO", i, integers=True)
        if L.LayerID.isalnum():
            LyrIDstr = L.LayerID
        else:
            warnstr = 'Layer # %i: Layer ID string "%s" is invalid, setting ID to layer number.' % (i, str(L.LayerID))
            if WARN(): print(warnstr)
            LyrIDstr = str(i)
            L.LayerID = LyrIDstr
        #end if(LayerID is alphanumeric)
        s = add(s, "LAYER_ID", LyrIDstr)
        s = add(s, "WAFER_SIDE", Defaults.Layer_WAFER_SIDE)
        s += "END_SECTION\n"
        s += "\n"

_I changed it to this (commented out the warning lines):_
    if DEBUG(): print("Generating Text Section 'LAYER_DEFINITION'")
    for i,L in enumerate(JobObj.LayerList):
        if DEBUG(): print( "Layer #%i, ID='%s'" %(i, str(L.LayerID) ) )
        s += "START_SECTION LAYER_DEFINITION\n"
        s = add(s, "LAYER_NO", i, integers=True)
        if L.LayerID.isalnum():
            LyrIDstr = L.LayerID
        else:
            LyrIDstr = L.LayerID
            # warnstr = 'Layer # %i: Layer ID string "%s" is invalid, setting ID to layer number.' % (i, str(L.LayerID))
            # if WARN(): print(warnstr)
            # LyrIDstr = str(i)
            # L.LayerID = LyrIDstr
        #end if(LayerID is alphanumeric)
        s = add(s, "LAYER_ID", LyrIDstr)
        s = add(s, "WAFER_SIDE", Defaults.Layer_WAFER_SIDE)
        s += "END_SECTION\n"
        s += "\n"

NOTE: the system allows 15 characters for Layer Names. Including letters, number, "_" and other things

**Comment by fyodr** [comment]
Can add sanitization in Layer.py or exportlib.py (as mentioned in #42). Which is better? 

It looks like exportlib currently allows python code to run with invalid names and then tries to correct at output. That seems like bad practice to me; probably better to throw an error so they can fix the bad name right away. But if users have bad names in their code, then throwing an error may be inconvenient.

@demisjohn your call.

**Comment by demisjohn** [comment]
@fyodr add sanitization code in the top-level Layer.py please. 
Exportlib should only perform formatting of the text file (and associated logic), not lithography/job-level logic.

**Comment by fyodr** [comment]
Sanitization added. I will test a little before commit.

Allowed characters:
ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-

(The input is forced to uppercase.) Anything else?

**Comment by demisjohn** [comment]
Ok, best is to test this by running a conversion on the tool (as the ASML conversion and exposure sometimes catches errors that aren’t caught in prior steps).

send me an Example01.txt file generated with this fix (modify layer names to have previously disallowed chars - eg. Longer than 15 chars, includes underscores dashes etc),
And include the plotting fix and we can try a test exposure to catch any errors in one shot.

**Comment by fyodr** [comment]
`Traceback (most recent call last):
  File "badexample.py", line 75, in <module>
    MetalLyr = MyJob.Layer( LayerID="IMMTOOOOOLLOOOONNGGG" )
  File 
...
    raise ValueError(errstr)
ValueError: Bad LayerID, IMMTOOOOOLLOOOONNGGG : LayerID must be 15 characters or less.`

`Traceback (most recent call last):
  File "badexample.py", line 75, in <module>
    MetalLyr = MyJob.Layer( LayerID="IHAVE@#$%@#" )
  File 
...
    raise ValueError(errstr)
ValueError: Bad LayerID, IHAVE@#$%@# : character @ is not allowed.
Allowed characters: ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-
`

**Comment by demisjohn** [comment]
Ok that is better - notify coder of issue so they can fix it, rather than changing it for them w/warning (the engineer approach - just make it work regardless of style!)

**Comment by fyodr** [comment]
Yes, that sounds good.

**Comment by fyodr** [comment]
Looking at Issue #3 , it looks like the allowed characters should be:
ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-_%+

Or are the allowed characters different for images and layers?
